# image: registry.gitlab.com/pages/hugo/hugo_extended:latest

# Set this if you intend to use Git submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production


build:
  stage: build
  tags:
    - blog
    - deploy
  script:
    - git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1
    - hugo -D
  artifacts:
    expire_in: 1 day
    paths:
      - site
  rules:
    - if: $CI_COMMIT_MESSAGE = /-draft$/
      when: never
    - when: always

deploy:
  stage: deploy
  tags:
    - blog
    - deploy
  script:
    - mkdir -p $HOME/blog
    - rm -rf $HOME/blog/site
    - docker rm -f hugo
    - cp -rf site $HOME/blog
    - cp Caddyfile $HOME/blog
    - docker run --name hugo -p 80:80 -p 443:443 -d -v ${HOME}/blog/Caddyfile:/etc/caddy/Caddyfile -v ${HOME}/blog/site:/var/www  -v ${HOME}/blog/config:/config -v ${HOME}/blog/data:/data -e TZ=Asia/Shanghai caddy
  dependencies:
    - build
  rules:
    - if: $CI_COMMIT_MESSAGE = /-draft$/
      when: never
    - when: always



 
