# image: registry.gitlab.com/pages/hugo/hugo_extended:latest

# Set this if you intend to use Git submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production


# default:
#   before_script:
#     - apk add --update --no-cache git go
#     - git submodule update --init --recursive
#     - hugo mod init gitlab.com/pages/hugo
#     - hugo mod get -u github.com/adityatelange/hugo-PaperMod

# test:
#   script:
#     - hugo
#   rules:
#     - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

# pages:
#   script:
#     - hugo
#   artifacts:
#     paths:
#       - public
#   rules:
#     - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH


build:
  stage: build
  tags:
    - blog
    - deploy
  script:
    - git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1
    - hugo -D
  artifacts:
    paths:
      - site


deploy:
  stage: deploy
  tags:
    - blog
    - deploy
  script:
    - rm -rf $HOME/blog/site
    - docker rm -f hugo
    - cp -rf site %HOME/blog
    - cp Caddyfile $HOME/blog
    - docker run --name hugo -p 80:80 -p 443:443 -d -v ${HOME}/blog/Caddyfile:/etc/caddy/Caddyfile -v ${HOME}/blog/site:/var/www  -v ${HOME}/blog/config:/config -v ${HOME}/blog/data:/data -e TZ=Asia/Shanghai caddy
  dependencies:
    - build



 
