# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:

image: docker:20.10.5-dind

stages:          # List of stages for jobs, and their order of execution
  - build

pre-build:
  stage: build
  tags:
   - blog       
  script:
    - git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1

build-static:
  stage: build
  tags:
    - blog
  image: klakegg/hugo
  before_script:
    - ls -l
    - ls themes -l
  script:
    - hugo
  artifacts:
    expire_in: 1 day
    paths:
      - public
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /draft/
      when: never
    - when: always

build-image:
  stage: build
  script:
    - ls
