variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  tags:
    - blog
    - deploy
  script:
    - git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1
    - hugo
  artifacts:
    paths:
      - public
 
