image: registry.gitlab.com/pages/hugo/hugo_extended:latest

# Set this if you intend to use Git submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production


# default:
#   before_script:
#     - apk add --update --no-cache git go
#     - git submodule update --init --recursive
#     - hugo mod init gitlab.com/pages/hugo
#     - hugo mod get -u github.com/adityatelange/hugo-PaperMod

# test:
#   script:
#     - hugo
#   rules:
#     - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

# pages:
#   script:
#     - hugo
#   artifacts:
#     paths:
#       - public
#   rules:
#     - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH



pages:
  tags:
    - blog
    - deploy
  script:
    - git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1
    - hugo -D
  artifacts:
    paths:
      - $CI_PROJECT_DIR/site

deploy:
  tags:
    - blog
    - deploy
  dependencies:
    - pages
  script:
    - ls site
 
