# image: registry.gitlab.com/pages/hugo/hugo_extended:latest

# Set this if you intend to use Git submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production


build-static:
  stage: build
  tags:
    - blog
    - deploy
  script:
    - git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1
    - docker run --rm -it -v $(pwd):/src klakegg/hugo
  artifacts:
    expire_in: 1 day
    paths:
      - site
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /draft/
      when: never
    - when: always

build-image:
  stage: build
  tags:
    - blog
    - deploy
  before_script:
    - echo $(docker login --username=515298386@qq.com registry.cn-hangzhou.aliyuncs.com --password=$ALI_DOCKER_PWD)
  script:
    - ls
    - docker build registry.cn-hangzhou.aliyuncs.com/hecvstyle/blog:$CI_COMMIT_SHORT_SHA -t .
    - docker tag registry.cn-hangzhou.aliyuncs.com/hecvstyle/blog:latest
  
deploy:
  stage: deploy
  tags:
    - blog
    - deploy
  script:

    - docker rm -f hugo
    - docker run -d -p 80:80 -p 443:443 -p 443:443/udp \
      -v ${HOME}/blog/data:/data \
      -v ${HOME}/blog/config:/config \
      registry.cn-hangzhou.aliyuncs.com/hecvstyle/blog \
      --name hugo
      -e TZ=Asia/Shanghai \
      caddy file-server --domain furywizz.xyz
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /draft/
      when: never
    - when: always



 
