name: Master branch push

on:
  push:
    branches:
    - master

jobs:
  post_request:
    name: deploy cf pages
    runs-on: ubuntu-latest
    steps:
    - name: Run curl command
      env: #  as an environment variable
        ci_trigger: ${{ secrets.CI_WEBHOOK }}
      run: |
        curl -X POST $ci_trigger
